version: "3"
services:
  dnsmasq:
    restart: always
    image: jpillora/dnsmasq:latest
    ports:
      - 53:53/udp
    networks:
      - web
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro

  traefik:
    restart: always
    image: traefik:1.7
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    depends_on:
      - dnsmasq
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.backend=traefik-ui
      - traefik.frontend.rule=Host:traefik.local.test
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml:ro
      - ./certs:/certs:ro

networks:
  web:
    external: true
