version: "3"
services:

  traefik:
    restart: always
    image: traefik:v2.4.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml:ro
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http,https
      - traefik.http.routers.traefik.rule=Host(`traefik.chatbot-v2.wogra.test`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=api@internal

networks:
  traefik:
    name: traefik
