version: "3"
services:
  traefik:
    restart: always
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.backend=traefik-ui
      - traefik.frontend.rule=Host:traefik.local.test
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml:ro
      - ./local-cert.pem:/local-cert.pem:ro
      - ./local-key.pem:/local-key.pem:ro

networks:
  web:
    external: true
