debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        certFile = "/local-cert.pem"
        keyFile = "/local-key.pem"
  [entryPoints.traefik]
  address = ":8080"

[api]
entryPoint = "traefik"
dashboard = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
