entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    network: traefik
  file:
    filename: /dynamic.yml
    watch: false

api:
  dashboard: true
  insecure: true

metrics:
  prometheus: {}
